---
- name: "Update packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install nodejs and npm dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

# Install pm2
- name: "install pm2"
  become: yes
  apt:
    name: pm2
    state: latest
