# Extract the zipped artifact into the EC2 instance, and then start the app.
---
- name : "show remote env"
  shell : env


- name: Upload artifact
  become: yes
  synchronize:
    src: ../../backend/dist
    dest: /home/ubuntu/udaappdir
    recursive: yes

- name: Copy modules
  become: yes
  synchronize:
    src: ../../backend/node_modules
    dest: home/ubuntu/udaappdir
    recursive: yes

- name: Start the app
  become: yes
  shell: pm2 start ~/udaappdir/main.js -f
  args:
    chdir: /home/ubuntu/udaappdir/dist
  environment:
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"