---
- name: Create directory
  file:
    path: /home/ubuntu/udaappdir
    state: directory

- name: Upload artifact
  copy:
    src: ~/project/.circleci/ansible/roles/deploy/files/dist.zip
    dest: /home/ubuntu/udaappdir

- name: Install unzip
  become: true
  apt:
    name: unzip
    state: present

# Extract the zipped artifact into the EC2 instance, and then start the app.
- name: extract artifact
  shell: |
    cd /home/ubuntu/udaappdir
    unzip /home/ubuntu/udaappdir/dist.zip
    npm install
    pm2 stop default
    pm2 start npm -- start
