# Extract the zipped artifact into the EC2 instance, and then start the app.
---
- name: Create directory
  file:
    path: udaappdir
    state: directory
    mode: 0755

- name: Upload artifact
  copy:
    src: ../../../../backend/artifact.tar.gz
    dest: udaappdir
    mode: 0644

- name: Extract artifact
  shell: cd ~/udaappdir && tar -xzvf artifact.tar.gz npm i

- name: Start the app
  shell: pm2 start ~/udaappdir/main.js --name udaapp -f